POST http://localhost:4001/api/accounts/insert
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImlhdCI6MTYyMDg2NDQzNCwiZXhwIjoxNjI4NjQwNDM0fQ._mmSYLO9_ik4YDtSj75-3IPxPkgUcmSqqDahr5zF9kw

{
  "type_account": "Ahorros",
  "id_client": 32
}