
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "dni": 1193543225,
  "email": "kevinstiven@gmail.com",
  "name_lastname": "Kevin Martinez",
  "username": "kevinstmartinez",
  "pass": "1123581321",
  "passConfirm": "1123581321",
  "id_bank": 2
}