
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "dni": 12840234,
  "email": "jhon@gmail.com",
  "name_lastname": "Jhon Doe",
  "username": "jhonde",
  "pass": "password",
  "passConfirm": "password",
  "id_bank": 1,
  "role": [
    "admin"
  ]
}
