
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "cedula": 1193543225,
  "nombres": "Jacinto Moreno",
  "email": "jacinto.moreno@gmail.com",
  "telefono": "3156935758",
  "pin": "0000" 
}

###

POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
  "dni": 219084890,
  "email": "any@gmail.com",
  "name_lastname": "Any Name",
  "username": "username",
  "pass": "password",
  "passConfirm": "password",
  "id_bank": 2
}
