
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
  "dni": 1193543225,
  "email": "kevin@gmail.com",
  "name_lastname": "Kevin Martinez",
  "username": "kevinstmartinez",
  "pass": "1123581321",
  "passConfirm": "1123581321",
  "id_bank": 1,
  "role": [
    "admin"
  ]
}

###

POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
  "dni": 219084890,
  "email": "any@gmail.com",
  "name_lastname": "Any Name",
  "username": "username",
  "pass": "password",
  "passConfirm": "password",
  "id_bank": 2
}
