
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "kevinstmartinez",
  "pass": "1123581321"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "username",
  "pass": "password"
}
