
POST http://localhost:4001/api/payments/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImlhdCI6MTYyMDg2NTEyNCwiZXhwIjoxNjI4NjQxMTI0fQ.StpqusLNkza7dlbLGP27AZxocZ37ANe8kjF8TquSySA


{
  "invoice_amount": 87000,
  "number_payment_references": "47047394880",
  "id_service": 23
}
