POST http://localhost:4001/api/services/insert
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsIm5hbWUiOiJLZXZpbiBNYXJ0aW5leiIsInVzZXJuYW1lIjoia2V2aW5zdG1hcnRpbmV6IiwiaWF0IjoxNjIyMTU5Njk2LCJleHAiOjE2Mjk5MzU2OTZ9.H6hybYOYTkbg4YqNdkWnovk00K5Xg9q_hT4ua4qFHvw

{
  "name": "Agua",
  "type_service": "public",
  "value": 60000,
  "id_account": 19
}

