POST http://localhost:4001/api/transfers/transfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImlhdCI6MTYyMDg2NDQzNCwiZXhwIjoxNjI4NjQwNDM0fQ._mmSYLO9_ik4YDtSj75-3IPxPkgUcmSqqDahr5zF9kw

{
  "amount": 1,
  "destiny_account_number": "047562",
  "origin_account_number": "084943"
}
